In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d=tf.constant(4)
# constant is a method in tensorflow which helps create a tensor
# The above is a 0 D Tensor.
# 4 is just an element in it.

print(tensor_zero_d)
# The output here tells us the element in the 0D tensor. shape is not defined.
# DType is the data type.

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_dim=tf.constant(4)

tensor_one_dim=tf.constant([2, 0,-3])
print(tensor_one_dim)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [7]:
tensor_two_d=tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [10]:
tensor_three_d=tf.constant([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [2,7,0]],

    [[5,8,0],
     [1,0,2]],

    [[2,1,9],
     [4,-3,32]]
    ])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 2  7  0]]

 [[ 5  8  0]
  [ 1  0  2]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [11]:
print(tensor_three_d.shape)

(4, 2, 3)


In [12]:
print(tensor_zero_dim.shape)

(3,)


In [13]:
print(tensor_two_d.shape)

(4, 3)


In [15]:
print(tensor_zero_d.shape)

()


In [16]:
print(tensor_three_d.ndim)
# ndim tells us that the tensor is a 3 dimensional tensor.
#ndim can be sued to check the dimensions of a tensor

3


In [18]:
# now we will create a 4 D tensor
# for this we will need multiple 3D Tensors

tensor_four_d=tf.constant([
  [
      [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [2,7,0]],

    [[5,8,0],
     [1,0,2]],

    [[2,1,9],
     [4,-3,32]]
  ],



  [
    [[4,5,4],
     [3,1,1]],

    [[0,2,5],
     [0,4,3]],

    [[3,2,4],
     [5,8,3]],

    [[8,2,5],
     [2,3,3]]
  ],



  [
    [[0,2,5],
     [5,3,1]],

    [[6,2,0],
     [-1,10,0]],

    [[0,5,1],
     [1,7,0]],

    [[3,8,7],
     [2,3,2]]
  ]
])

print(tensor_four_d)
#now we have a 4d D Tensor with a combination of 3 3D Tensors

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 2  7  0]]

  [[ 5  8  0]
   [ 1  0  2]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]


 [[[ 0  2  5]
   [ 5  3  1]]

  [[ 6  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 2  3  2]]]], shape=(3, 4, 2, 3), dtype=int32)


In [21]:
tensor_two_dim=tf.constant([
 [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8],
], dtype=tf.float16)
print(tensor_two_dim)

tf.Tensor(
[[ 1.  2.  0.]
 [ 3.  5. -1.]
 [ 1.  5.  6.]
 [ 2.  3.  8.]], shape=(4, 3), dtype=float16)


In [22]:
# there are multiple datatypes in tensorflow.
# When needed do check out the documentation for the different types of tensors
# https://www.tensorflow.org/tutorials/quickstart/beginner
# https://www.tensorflow.org/guide/basics

In [28]:
# if you want to chnage the data type of the tensor elements then we got to use the  'cast method'
tensor_one_d=tf.constant([2,0,-4,3,80], dtype=tf.int16)
casted_tensor=tf.cast(tensor_one_d, dtype=tf.float16)
casted_tensor_bool=tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor)
print(casted_tensor_bool)
# observe that, whereever there is non-zero element, it prints True

tf.Tensor([ 2  0 -4  3 80], shape=(5,), dtype=int16)
tf.Tensor([ 2.  0. -4.  3. 80.], shape=(5,), dtype=float16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)
